class ErrorCode:
    CHECKLIST_NO_ENCONTRADO = "El checklist no fue encontrado."
    TAREA_CHECKLIST_NO_ENCONTRADA = "La tarea no fue encontrada en este checklist."
    TAREA_YA_COMPLETADA = "La tarea ya fue completada previamente."
    RESPONSABLE_NO_ENCONTRADO = "El responsable asignado no existe o no está registrado."
    RESPONSABLE_INACTIVO = "El responsable asignado no se encuentra activo."
    CHECKLIST_FECHA_FUTURA = "No se puede generar un checklist para una fecha posterior a la actual."
    CHECKLIST_FECHA_PASADA = "No se puede generar un checklist para una fecha anterior a la actual. Solo se permite generar para el día de hoy."
    NO_HAY_TAREAS_CORRESPONDIENTES = "No hay tareas de limpieza que correspondan ejecutarse en la fecha indicada."
    IMAGEN_NO_ENCONTRADA = "La imagen solicitada no fue encontrada."
    FORMATO_IMAGEN_INVALIDO = "El archivo enviado no es una imagen válida."
    CHECKLIST_NO_MODIFICABLE = "El checklist se encuentra completado o vencido y no admite modificaciones."
    RANGO_FECHAS_INVALIDO = "La fecha 'desde' no puede ser posterior a la fecha 'hasta'."
    INSUMO_QUIMICO_INACTIVO = "El insumo químico seleccionado se encuentra inactivo."
    INSUMO_QUIMICO_NO_ENCONTRADO = "Uno de los insumos químicos seleccionados no existe."
    CANTIDAD_CONSUMO_INVALIDA = "La cantidad consumida debe ser mayor a cero."