class ErrorCode:
    FECHA_DE_REALIZACION="INGRESE LA FECHA DE REALIZACION DEL PLAN"
    FORMATO_INVALIDO="EL FORMATO DEL ARCHIVO ES INVALIDO"
    TAMANIO_ERROR="SOBRE PASO EL TAMANIO PERMITIDO"
    CALIBRACION_NO_ECONTRADA="NO SE ENCONTRA LA CALIBRACION REALIZAADA"
